# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_railway_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('date', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('time', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('category', models.CharField(blank=True, choices=[('event', 'Events'), ('public', 'Public Displays')], max_length=100)),
                ('position', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
