# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20171018_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railway',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
