# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20171025_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railway',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
